# Environment-Specific Observability Stack
# Usage: kubectl apply -f observability-stack.yaml -l environment=dev|prod

---
# Grafana Dashboard - Development (Basic)
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-dev
  namespace: co2-assistant
  labels:
    environment: dev
    app: grafana
data:
  co2-assistant-dev.json: |
    {
      "dashboard": {
        "title": "CO2 Assistant - Development",
        "panels": [
          {
            "title": "Request Rate",
            "type": "graph",
            "targets": [{"expr": "rate(http_requests_total[5m])"}]
          },
          {
            "title": "Response Time",
            "type": "graph", 
            "targets": [{"expr": "http_request_duration_seconds"}]
          }
        ]
      }
    }

---
# Grafana Dashboard - Production (Comprehensive)
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-prod
  namespace: co2-assistant
  labels:
    environment: prod
    app: grafana
data:
  co2-assistant-prod.json: |
    {
      "dashboard": {
        "title": "CO2 Assistant - Production SLA Dashboard",
        "panels": [
          {
            "title": "SLA Availability (99.9% target)",
            "type": "stat",
            "targets": [{"expr": "slo:availability_rate"}]
          },
          {
            "title": "Error Rate (< 0.1% target)",
            "type": "graph",
            "targets": [{"expr": "rate(http_requests_total{status=~\"5..\"}[5m])"}]
          },
          {
            "title": "Latency P95 (< 500ms target)",
            "type": "graph",
            "targets": [{"expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))"}]
          },
          {
            "title": "Resource Utilization",
            "type": "graph",
            "targets": [
              {"expr": "rate(container_cpu_usage_seconds_total[5m])"},
              {"expr": "container_memory_usage_bytes"}
            ]
          }
        ]
      }
    }

---
# Jaeger Tracing - Production Only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: co2-assistant
  labels:
    environment: prod
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
        - containerPort: 14268
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
