apiVersion: apps/v1
kind: Deployment
metadata:
  name: co2-assistant
  namespace: co2-assistant
  labels:
    app: co2-assistant
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: co2-assistant
  template:
    metadata:
      labels:
        app: co2-assistant
        version: v1
    spec:
      containers:
      - name: co2-assistant
        image: us-central1-docker.pkg.dev/gke10-ai-hackathon/co2-assistant-repo/co2-assistant:latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: co2-assistant-secrets
              key: google-ai-api-key
        - name: GOOGLE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: co2-assistant-secrets
              key: google-project-id
        - name: BOUTIQUE_BASE_URL
          value: "http://ob-proxy.co2-assistant.svc.cluster.local:80"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: co2-assistant-service
  namespace: co2-assistant
  labels:
    app: co2-assistant
spec:
  selector:
    app: co2-assistant
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: co2-assistant-secrets
  namespace: co2-assistant
type: Opaque
data:
  google-ai-api-key: ""  # Base64 encoded API key
  google-project-id: ""   # Base64 encoded project ID
