---
# Online Boutique Proxy - enables cross-namespace routing from co2-assistant to default namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-proxy
  namespace: co2-assistant
  labels:
    app: ob-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ob-proxy
  template:
    metadata:
      labels:
        app: ob-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
            ephemeral-storage: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 256Mi
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: nginx-conf
        configMap:
          name: ob-proxy-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ob-proxy-config
  namespace: co2-assistant
data:
  default.conf: |
    server {
      listen 80;
      resolver kube-dns.kube-system.svc.cluster.local valid=5s;
      set $upstream http://frontend.online-boutique.svc.cluster.local:80;

      location /ob-images/ {
        rewrite /ob-images/(.*) /$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffers 32 64k;
        proxy_buffer_size 64k;
        proxy_busy_buffers_size 128k;
        proxy_read_timeout 75s;
        proxy_send_timeout 75s;
        proxy_connect_timeout 30s;
        proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
      }

      location / {
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffers 32 64k;
        proxy_buffer_size 64k;
        proxy_busy_buffers_size 128k;
        proxy_read_timeout 75s;
        proxy_send_timeout 75s;
        proxy_connect_timeout 30s;
        proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
      }

      # Proxy Online Boutique backend services for the assistant

      # Cart service (HTTP)
      location /cartservice/ {
        proxy_pass http://cartservice.online-boutique.svc.cluster.local:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Checkout service (HTTP)
      location /checkoutservice/ {
        proxy_pass http://checkoutservice.online-boutique.svc.cluster.local:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Recommendation service (HTTP)
      location /recommendationservice/ {
        proxy_pass http://recommendationservice.online-boutique.svc.cluster.local:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Currency service (HTTP)
      location /currencyservice/ {
        proxy_pass http://currencyservice.online-boutique.svc.cluster.local:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: ob-proxy
  namespace: co2-assistant
  labels:
    app: ob-proxy
spec:
  selector:
    app: ob-proxy
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
